### ISSUE TITLE
DBの起動時にdocker composeのネットワークでプライベートアドレスが使われてしまう

### ISSUE THREAD

**Issue by azu4005** [Rits-Interaction-Laboratory/shigure_core#78]
``` 
  cd ~/ros2_ws/src/shigure_core/shigure_core/resource/db 
  docker-compose up
```
でデータベースを起動した際に、docker networkでdb_defaultというbridgeネットワークがつくられ、そのネットワークに使用されないはずのプライベートアドレス（僕の場合は172.18.0.1のアドレス）が優先され、外部ネットワークのアドレスではなくプライベートアドレスをソースアドレスにして通信してしまう現象が起きた。

↓

そのため、ROS2ノード(bg_subtraction)を起動すると、subscribeされた側のrs_cameraはこのアドレスに対して画像を含んだDDS/UDPパケットを投げつけ、camera1のNUC上のルーティングテーブルではdefaultルートにマッチするので外向きデフォルトルータにUDPパケットが大量に常に投げつけられている状況が発生した。

**Comment by azu4005** [comment]
これが起こる原因としては、ros2がノードを起動するときに最も広帯域かつ一番レイテンシの少ないインターフェースを自動的に選んで起動するため、プライベートアドレスをアドレスにして通信してしまったらしい。

**Comment by azu4005** [comment]
この問題を避けるためには、Docker Composeを使うときに外部ネットワークを使用して、Dockerhostマシンとdb_defaultネットワーク内のコンテナ間で通信する必要がある。
外部ネットワークを使用すると、ネットワーク内のコンテナは、Dockerホストマシンのネットワークインターフェースに割り当てられたIPアドレスを使用してアクセスすることができる。

Docker Composeで外部ネットワークを使用する方法を以下に記述する。

1.　Composeファイルで、外部ネットワークを定義します。以下は、外部ネットワークを定義する例です
``` 
yamlファイル
version: '3'

services:
    image: mysql:8
    ・・・
    networks:
      - <使用するネットワーク名>
networks:
    <使用するネットワーク名>:
      external: true
```
上記の例では、dbサービスが<使用するネットワーク名>のネットワークに接続されます。<使用するネットワーク名>は、外部ネットワークであるため、external: trueを設定することでdocker-compose.yml 内ではなく、外部で定義されているネットワークを探すように指定します。

2. Composeファイルを使用してサービスを起動します。以下のように、docker-compose upコマンドを使用します。
```
docker-compose up --build
```
これで、指定したネットワークに接続されたdbサービスが実行されます。このサービスは、外部ネットワークに接続されているため、DockerホストマシンのIPアドレスを使用して、Dockerホストマシンからアクセスすることができ。

**Comment by azu4005** [comment]
もし、Docker ファイルのnetworkが再設定したのに、外部のネットワークで通信できておらず、
```
ERROR: Encountered errors while bringing up the project.
```
が起きた場合は、再設定前の情報を参照してしまっているため、エラーになって起動しない
```
docker-compose down
```
でdockerコンテナを削除してからコンテナ起動を行うと設定が更新され、起動できる。

**Comment by htm2323** [comment]
DB用のDokcerfileを作成し，`docker build`→`docker run`で1コンテナずつ起動するようにして，バグを回避するようにした．
#70
